package com.hust.hotelproject.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.hust.hotelproject.controller.*;
import com.hust.hotelproject.model.dao.*;
import com.hust.hotelproject.model.entity.*;
import javax.swing.JOptionPane;
import com.hust.hotelproject.util.*;
import static java.lang.Long.parseLong;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form SecondFrame
     */
    public AdminView() {
        initComponents();
    }
    
    private EmployeeController employeeController = new EmployeeController();
    private RoomController roomController = new RoomController();
    private ServiceController serviceController = new ServiceController();
    public static User userLogin = new User();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        nvPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findNvButton = new javax.swing.JButton();
        addNvButton = new javax.swing.JButton();
        deleteNvButton = new javax.swing.JButton();
        dxButton1 = new javax.swing.JButton();
        listNvButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameNvTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sexNvCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        roleNvTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nvTable = new javax.swing.JTable();
        nameLabelTxt = new javax.swing.JLabel();
        roomPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dxButton2 = new javax.swing.JButton();
        findRoomButton = new javax.swing.JButton();
        addRoomButton = new javax.swing.JButton();
        deleteRoomButton = new javax.swing.JButton();
        listRoomButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusRoomCB = new javax.swing.JComboBox<>();
        nameRoomTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        typeRoomCB = new javax.swing.JComboBox<>();
        priceRoomTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        priceLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        svPanel = new javax.swing.JPanel();
        dxButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        findSvButton = new javax.swing.JButton();
        addSvButton = new javax.swing.JButton();
        deleteSvButton = new javax.swing.JButton();
        listSvButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nameSvTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        priceSvTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        svTabel = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        employeeTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dxButton4 = new javax.swing.JButton();
        passTxt2 = new javax.swing.JPasswordField();
        passTxt1 = new javax.swing.JPasswordField();
        userLabel = new javax.swing.JLabel();
        pass1Label = new javax.swing.JLabel();
        pass2Label = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleCB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dxButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        totalIncomeTxt = new javax.swing.JLabel();
        regularCustomerTxt = new javax.swing.JLabel();
        vipCustomerTxt = new javax.swing.JLabel();
        regularRoom = new javax.swing.JLabel();
        rentalTimeTxt = new javax.swing.JLabel();
        dxButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELLO ADMIN");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(907, 551));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Employee Manage");

        findNvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findNvButton.setText("Search");
        findNvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNvButtonActionPerformed(evt);
            }
        });

        addNvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addNvButton.setText("Insert");
        addNvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNvButtonActionPerformed(evt);
            }
        });

        deleteNvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteNvButton.setText("Delete");
        deleteNvButton.setMaximumSize(new java.awt.Dimension(109, 37));
        deleteNvButton.setMinimumSize(new java.awt.Dimension(109, 37));
        deleteNvButton.setPreferredSize(new java.awt.Dimension(109, 37));
        deleteNvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNvButtonActionPerformed(evt);
            }
        });

        dxButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton1.setText("Logout");
        dxButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton1ActionPerformed(evt);
            }
        });

        listNvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listNvButton.setText("Update");
        listNvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listNvButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name");

        nameNvTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameNvTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameNvTxtMouseClicked(evt);
            }
        });
        nameNvTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNvTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sex");

        sexNvCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sexNvCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Role");

        roleNvTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        nvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sex", "Role"
            }
        ));
        nvTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(nvTable);

        javax.swing.GroupLayout nvPanelLayout = new javax.swing.GroupLayout(nvPanel);
        nvPanel.setLayout(nvPanelLayout);
        nvPanelLayout.setHorizontalGroup(
            nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(nvPanelLayout.createSequentialGroup()
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nvPanelLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(80, 80, 80)
                        .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nvPanelLayout.createSequentialGroup()
                                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexNvCB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nvPanelLayout.createSequentialGroup()
                                        .addComponent(nameNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addNvButton)
                                            .addComponent(nameLabelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 103, Short.MAX_VALUE))
                            .addGroup(nvPanelLayout.createSequentialGroup()
                                .addComponent(roleNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvPanelLayout.createSequentialGroup()
                                .addComponent(findNvButton)
                                .addGap(434, 434, 434))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(184, 184, 184)))))
                .addComponent(dxButton1))
            .addGroup(nvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteNvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listNvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        nvPanelLayout.setVerticalGroup(
            nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nvPanelLayout.createSequentialGroup()
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton1)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNvButton)
                    .addComponent(findNvButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(35, 35, 35)
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexNvCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nvPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(nvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nvPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(deleteNvButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listNvButton)
                        .addGap(126, 126, 126))))
        );

        jTabbedPane1.addTab("Employee", nvPanel);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Room Manage");

        dxButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton2.setText("Logout");
        dxButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton2ActionPerformed(evt);
            }
        });

        findRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findRoomButton.setText("Search");
        findRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomButtonActionPerformed(evt);
            }
        });

        addRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addRoomButton.setText("Insert");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        deleteRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteRoomButton.setText("Delete");
        deleteRoomButton.setMaximumSize(new java.awt.Dimension(109, 37));
        deleteRoomButton.setMinimumSize(new java.awt.Dimension(109, 37));
        deleteRoomButton.setPreferredSize(new java.awt.Dimension(109, 37));
        deleteRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomButtonActionPerformed(evt);
            }
        });

        listRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listRoomButton.setText("Update");
        listRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRoomButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Type");

        statusRoomCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusRoomCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "F" }));

        nameRoomTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameRoomTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameRoomTxtMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Price");

        typeRoomCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typeRoomCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        priceRoomTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceRoomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceRoomTxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Status");

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(roomTable);

        javax.swing.GroupLayout roomPanelLayout = new javax.swing.GroupLayout(roomPanel);
        roomPanel.setLayout(roomPanelLayout);
        roomPanelLayout.setHorizontalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roomPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roomPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(findRoomButton)
                                .addGap(163, 163, 163)
                                .addComponent(addRoomButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dxButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(roomPanelLayout.createSequentialGroup()
                                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7))
                                            .addGroup(roomPanelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel9)))
                                        .addGap(95, 95, 95)
                                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(statusRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(typeRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(roomPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(listRoomButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteRoomButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(94, 94, 94))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roomPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roomPanelLayout.setVerticalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRoomButton)
                    .addComponent(findRoomButton))
                .addGap(36, 36, 36)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(nameRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(typeRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(priceRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addComponent(listRoomButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Room", roomPanel);

        dxButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton3.setText("Logout");
        dxButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Service Manage");

        findSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findSvButton.setText("Search");
        findSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findSvButtonActionPerformed(evt);
            }
        });

        addSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addSvButton.setText("Insert");
        addSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSvButtonActionPerformed(evt);
            }
        });

        deleteSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteSvButton.setText("Delete");
        deleteSvButton.setMaximumSize(new java.awt.Dimension(109, 37));
        deleteSvButton.setMinimumSize(new java.awt.Dimension(109, 37));
        deleteSvButton.setPreferredSize(new java.awt.Dimension(109, 37));
        deleteSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSvButtonActionPerformed(evt);
            }
        });

        listSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listSvButton.setText("Update");
        listSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSvButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Name");

        nameSvTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameSvTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameSvTxtMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Price");

        priceSvTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        svTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        jScrollPane3.setViewportView(svTabel);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout svPanelLayout = new javax.swing.GroupLayout(svPanel);
        svPanel.setLayout(svPanelLayout);
        svPanelLayout.setHorizontalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svPanelLayout.createSequentialGroup()
                .addGap(80, 173, Short.MAX_VALUE)
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                        .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(svPanelLayout.createSequentialGroup()
                                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(svPanelLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(findSvButton))
                                    .addGroup(svPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(85, 85, 85)
                                        .addComponent(priceSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(svPanelLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(svPanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(addSvButton))))
                            .addGroup(svPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(77, 77, 77)
                                .addComponent(nameSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(226, 226, 226)
                        .addComponent(dxButton3))))
        );
        svPanelLayout.setVerticalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svPanelLayout.createSequentialGroup()
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton3)
                    .addComponent(jLabel10))
                .addGap(46, 46, 46)
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSvButton)
                    .addComponent(findSvButton))
                .addGap(42, 42, 42)
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(nameSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(svPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12))
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(listSvButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteSvButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service", svPanel);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(220, 39, 39));
        jLabel13.setText("User manage");
        jLabel13.setToolTipText("");
        jLabel13.setMaximumSize(new java.awt.Dimension(455, 57));
        jLabel13.setMinimumSize(new java.awt.Dimension(455, 57));
        jLabel13.setPreferredSize(new java.awt.Dimension(455, 57));

        jLabel14.setText("User Name");

        jLabel15.setText("Password");

        jLabel16.setText("Password");

        jLabel17.setText("Role");

        jLabel18.setText("Employee Id");

        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        employeeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dxButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton4.setText("Logout");
        dxButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton4ActionPerformed(evt);
            }
        });

        passTxt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTxt2MouseClicked(evt);
            }
        });

        passTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTxt1MouseClicked(evt);
            }
        });
        passTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxt1ActionPerformed(evt);
            }
        });

        roleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "employee" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(passTxt1)
                    .addComponent(userTxt)
                    .addComponent(employeeTxt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dxButton4)
                .addGap(52, 52, 52)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(passTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pass1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(passTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pass2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employeeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanel1);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Rental Times ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("VIP Customer");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Regular Customer");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Total Income ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("Information");

        dxButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton5.setText("Logout");
        dxButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton5ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Regular Room");

        totalIncomeTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        regularCustomerTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vipCustomerTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        regularRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rentalTimeTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dxButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton6.setText("Show");
        dxButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(dxButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(totalIncomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(regularRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(regularCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vipCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rentalTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(358, 358, 358))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dxButton5)
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addComponent(totalIncomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(rentalTimeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(vipCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(regularCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regularRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(dxButton6)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Infomation", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("HELLO ADMIN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        resetText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void passTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxt1ActionPerformed

    private void passTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxt1MouseClicked

    private void passTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxt2MouseClicked
        passTxt2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxt2MouseClicked

    private void dxButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_dxButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        String username = userTxt.getText();
        char[] s = passTxt1.getPassword();
        String passwordd = new String(s);

        if (username.equals("")) {
            userLabel.setText("Enter username");
            return;
        } else {
            userLabel.setText("");
        }
        if (passwordd.equals("")) {
            pass1Label.setText("Enter password");
            return;
        } else {
            pass1Label.setText("");
        }
        char[] s2 = passTxt2.getPassword();
        String password2 = new String(s2);
        if(!passwordd.equals(password2)) {
            pass2Label.setText("Wrong password");
            return;
        } else {
            pass2Label.setText("");
        }

        String password = PasswordHashing.hashing(passwordd);

        String role = (String) roleCB.getSelectedItem();
        if (role.equals("")) {
            roleLabel.setText("Enter role");
            return;
        } else {
            roleLabel.setText("");
        }

        String employeeId = employeeTxt.getText();
        if(employeeId.equals("")) {
            employeeLabel.setText("Enter employee");
            return;
        } else {
            employeeLabel.setText("");
        }

        User user = new User(username, password, role, employeeId);
        boolean check = new UserDao().insertUser(user);
        if(check) {
            Logger.info("Insert success");
            JOptionPane.showMessageDialog(this, "Insert Success");

        } else {
            Logger.error("Insert false");
            JOptionPane.showMessageDialog(this, "Insert false");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void employeeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTxtActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void listSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSvButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = svTabel.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Service");
                    return;
        }

        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();
        String serviceId = (String) model.getValueAt(selectedRow, 0);
        Logger.info(serviceId);
        serviceController.deleteService(serviceId);

        String name = nameSvTxt.getText();
        String price = priceSvTxt.getText();
        if(!isNumeric(price) || price.isEmpty()) {
            priceLabel.setText("Insert a digit");
            return;
        }
        Service service = new Service(serviceId, name, parseLong(price));
        boolean check = serviceController.insertService(service);
        if(check) {
            Logger.info("Insert success");

        } else {
            Logger.error("Insert false");
        }
        reloadTableService();
    }//GEN-LAST:event_listSvButtonActionPerformed

    private void deleteSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSvButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = svTabel.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Service");
                    return;
        }

        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();
        String serviceId = (String) model.getValueAt(selectedRow, 0);
        Logger.info(serviceId);
        serviceController.deleteService(serviceId);
        reloadTableService();
    }//GEN-LAST:event_deleteSvButtonActionPerformed

    private void addSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSvButtonActionPerformed
        // TODO add your handling code here:
        String name = nameSvTxt.getText();
        if(name.equals("")) {
            jLabel27.setText("Input name");
            return;
        } else {
            jLabel27.setText("");
        }
        String price = priceSvTxt.getText();
        if(!isNumeric(price) || price.isEmpty()) {
            jLabel26.setText("Insert a digit");
            return;
        }
        Service service = new Service(IdGenerator.generateEmployeeId(6), name, parseLong(price));
        boolean check = serviceController.insertService(service);
        if(check) {
            Logger.info("Insert success");

        } else {
            Logger.error("Insert false");
        }
        reloadTableService();
    }//GEN-LAST:event_addSvButtonActionPerformed

    private void findSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findSvButtonActionPerformed
        // TODO add your handling code here:
        String name = nameSvTxt.getText();
        List<Service> listService = serviceController.findService(name);
        showDataDv(listService);
    }//GEN-LAST:event_findSvButtonActionPerformed

    private void dxButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton3ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_dxButton3ActionPerformed

    private void priceRoomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceRoomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceRoomTxtActionPerformed

    private void listRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRoomButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = roomTable.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Room");
                    return;
        }

        DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
        String roomId = (String) model.getValueAt(selectedRow, 0);
        String price = priceRoomTxt.getText();
        if(!isNumeric(price) || price.isEmpty()) {
            priceLabel.setText("Enter a value");
            return;
        }
        roomController.deleteRoom(roomId);
        Room room = new Room(roomId, (String) typeRoomCB.getSelectedItem(), parseLong(price), (String) statusRoomCB.getSelectedItem(), nameRoomTxt.getText());
        boolean result = roomController.insertRoom(room);
        String keyWord = nameRoomTxt.getText();
        List<Room> listRoom = roomController.findRoom(keyWord);
        showDataRoom(listRoom);
    }//GEN-LAST:event_listRoomButtonActionPerformed

    private void deleteRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = roomTable.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Room");
                    return;
        }
        DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
        String roomId = (String) model.getValueAt(selectedRow, 0);
        Logger.info(roomId);

        roomController.deleteRoom(roomId);
        reloadTableRoom();
    }//GEN-LAST:event_deleteRoomButtonActionPerformed

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        // TODO add your handling code here:
        String name = nameRoomTxt.getText();
        if(name.equals("")) {
            nameLabel.setText("Input name");
            return;
        } else {
            nameLabel.setText("");
        }

        String price = priceRoomTxt.getText();
        if(!isNumeric(price) || price == null) {
            priceLabel.setText("Enter a value");
            return;
        }

        Room room = new Room(IdGenerator.generateEmployeeId(6), (String) typeRoomCB.getSelectedItem(), parseLong(price), (String) statusRoomCB.getSelectedItem(), name);
        boolean result = roomController.insertRoom(room);
        reloadTableRoom();
    }//GEN-LAST:event_addRoomButtonActionPerformed

    private void findRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomButtonActionPerformed
        String keyWord = nameRoomTxt.getText();
        List<Room> listRoom = roomController.findRoom(keyWord);
        showDataRoom(listRoom);
    }//GEN-LAST:event_findRoomButtonActionPerformed

    private void dxButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_dxButton2ActionPerformed

    private void nameNvTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNvTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameNvTxtActionPerformed

    private void listNvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listNvButtonActionPerformed
        int selectedRow = nvTable.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Employee");
                    return;
        }

        DefaultTableModel model = (DefaultTableModel) nvTable.getModel();
        String employeeId = (String) model.getValueAt(selectedRow, 0);
        employeeController.deleteEmployee(employeeId);
        Employee employee = new Employee(employeeId, nameNvTxt.getText(), (String)sexNvCB.getSelectedItem(), roleNvTxt.getText());
        boolean result =  employeeController.insertEmployee(employee);
        String keyword = nameNvTxt.getText();
        List<Employee> employees = employeeController.findEmployee(keyword);

        showDataNv(employees);
    }//GEN-LAST:event_listNvButtonActionPerformed

    private void dxButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_dxButton1ActionPerformed

    private void deleteNvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNvButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = nvTable.getSelectedRow();
        if(selectedRow == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Not choose Employee");
                    return;
        }

        DefaultTableModel model = (DefaultTableModel) nvTable.getModel();
        String employeeId = (String) model.getValueAt(selectedRow, 0);

        employeeController.deleteEmployee(employeeId);
        reloadTableNv();
    }//GEN-LAST:event_deleteNvButtonActionPerformed

    private void addNvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNvButtonActionPerformed
        String name = nameNvTxt.getText();
        if(name.equals("")) {
            nameLabelTxt.setText("Input name");
            return;
        } else {
            nameLabelTxt.setText("");
        }

        Employee employee = new Employee(IdGenerator.generateEmployeeId(6), name, (String)sexNvCB.getSelectedItem(), roleNvTxt.getText());
        boolean result =  employeeController.insertEmployee(employee);
        reloadTableNv();
    }//GEN-LAST:event_addNvButtonActionPerformed

    private void findNvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNvButtonActionPerformed
        String keyword = nameNvTxt.getText();
        List<Employee> employees = employeeController.findEmployee(keyword);

        showDataNv(employees);
    }//GEN-LAST:event_findNvButtonActionPerformed

    private void dxButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Logout success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dxButton5ActionPerformed

    private void dxButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton6ActionPerformed
        // TODO add your handling code here:
        BillDao billDao = new BillDao();
        BookingDao bookingDao = new BookingDao();
        long totalIncome = billDao.totalIncome();
        String totalIncomeStr = String.valueOf(totalIncome);
        totalIncomeTxt.setText(totalIncomeStr);
        
        long rentalTimes = bookingDao.rentalTimes();
        String rentalTimesStr = String.valueOf(rentalTimes);
        rentalTimeTxt.setText(rentalTimesStr);
        
        
        vipCustomerTxt.setText(billDao.vipCustomer());
        regularCustomerTxt.setText(billDao.regularCustomer());
        regularRoom.setText(bookingDao.regularRoom());
        
    }//GEN-LAST:event_dxButton6ActionPerformed

    private void nameNvTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameNvTxtMouseClicked
        nameNvTxt.setText("");
        roleNvTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameNvTxtMouseClicked

    private void nameRoomTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameRoomTxtMouseClicked
        nameRoomTxt.setText("");
        priceRoomTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRoomTxtMouseClicked

    private void nameSvTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSvTxtMouseClicked
        nameSvTxt.setText("");
        priceSvTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSvTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public void runFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminView secondFrame = new AdminView();
                secondFrame.setVisible(true);
                secondFrame.setLocationRelativeTo(null);
                secondFrame.reloadTableNv();
                secondFrame.reloadTableRoom();
                secondFrame.reloadTableService();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNvButton;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JButton addSvButton;
    private javax.swing.JButton deleteNvButton;
    private javax.swing.JButton deleteRoomButton;
    private javax.swing.JButton deleteSvButton;
    private javax.swing.JButton dxButton1;
    private javax.swing.JButton dxButton2;
    private javax.swing.JButton dxButton3;
    private javax.swing.JButton dxButton4;
    private javax.swing.JButton dxButton5;
    private javax.swing.JButton dxButton6;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JTextField employeeTxt;
    private javax.swing.JButton findNvButton;
    private javax.swing.JButton findRoomButton;
    private javax.swing.JButton findSvButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listNvButton;
    private javax.swing.JButton listRoomButton;
    private javax.swing.JButton listSvButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabelTxt;
    private javax.swing.JTextField nameNvTxt;
    private javax.swing.JTextField nameRoomTxt;
    private javax.swing.JTextField nameSvTxt;
    private javax.swing.JPanel nvPanel;
    private javax.swing.JTable nvTable;
    private javax.swing.JLabel pass1Label;
    private javax.swing.JLabel pass2Label;
    private javax.swing.JPasswordField passTxt1;
    private javax.swing.JPasswordField passTxt2;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceRoomTxt;
    private javax.swing.JTextField priceSvTxt;
    private javax.swing.JLabel regularCustomerTxt;
    private javax.swing.JLabel regularRoom;
    private javax.swing.JLabel rentalTimeTxt;
    private javax.swing.JComboBox<String> roleCB;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JTextField roleNvTxt;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JTable roomTable;
    private javax.swing.JComboBox<String> sexNvCB;
    private javax.swing.JComboBox<String> statusRoomCB;
    private javax.swing.JPanel svPanel;
    private javax.swing.JTable svTabel;
    private javax.swing.JLabel totalIncomeTxt;
    private javax.swing.JComboBox<String> typeRoomCB;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel vipCustomerTxt;
    // End of variables declaration//GEN-END:variables

    public void reloadTableNv() {
        List<Employee> listEmployee = employeeController.returnAllEmployee();
        DefaultTableModel model = (DefaultTableModel) nvTable.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Employee employee : listEmployee) {
            model.addRow(new Object[]{employee.getEmployeeId(), employee.getName(), employee.getSex(), employee.getRole()});
        }
        
    }
    
    
    private void showDataNv(List<Employee> listEmployee) {
        DefaultTableModel model = (DefaultTableModel) nvTable.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Employee employee : listEmployee) {
            model.addRow(new Object[]{employee.getEmployeeId(), employee.getName(), employee.getSex(), employee.getRole()});
        }
    }
    private void showDataDv(List<Service> listService) {
        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Service service : listService) {
            model.addRow(new Object[]{service.getServiceId(), service.getName(), service.getPrice()});
        }
    }
    public void reloadTableRoom() {
        List <Room> listRoom = roomController.returnAllRoom();
        DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Room room : listRoom) {
            model.addRow(new Object[]{room.getRoomId(), room.getName(), room.getType(), room.getPrice(), room.getStatus()});
        }
        
    }
    public void reloadTableService() {
        List <Service> listService = serviceController.returnAllService();
        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Service service : listService) {
            model.addRow(new Object[]{service.getServiceId(), service.getName(), service.getPrice()});
        }
        
    }
    
    private void showDataRoom(List<Room> listRoom) {
        DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
        
        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }   
        
        // Add new data
        for (Room room : listRoom) {
            model.addRow(new Object[]{room.getRoomId(), room.getName(), room.getType(), room.getPrice(), room.getStatus()});
        }
    }
    
    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }
    
    public void resetText() {
        nameNvTxt.setText("");
        roleNvTxt.setText("");
        nameRoomTxt.setText("");
        priceRoomTxt.setText("");
        nameSvTxt.setText("");
        priceSvTxt.setText("");
        nameLabelTxt.setText("");
        nameLabel.setText("");
        priceLabel.setText("");
        userTxt.setText("");
        passTxt1.setText("");
        passTxt2.setText("");
        employeeTxt.setText("");
        userLabel.setText("");
        pass1Label.setText("");
        pass2Label.setText("");
        roleLabel.setText("");
        employeeLabel.setText("");
    }
}
