package com.hust.hotelproject.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.hust.hotelproject.controller.BookingController;
import com.hust.hotelproject.controller.CustomerController;
import com.hust.hotelproject.controller.RoomController;
import com.hust.hotelproject.controller.ServiceController;
import com.hust.hotelproject.model.dao.BillDao;
import com.hust.hotelproject.model.dao.RoomDao;
import com.hust.hotelproject.model.entity.Bill;
import com.hust.hotelproject.model.entity.Booking;
import com.hust.hotelproject.model.entity.Customer;
import com.hust.hotelproject.model.entity.Room;
import com.hust.hotelproject.model.entity.Service;
import com.hust.hotelproject.model.entity.User;
import com.hust.hotelproject.util.ExportBill;
import com.hust.hotelproject.util.IdGenerator;
import com.hust.hotelproject.util.Logger;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
//import java.time.*;

/**
 *
 * @author Admin
 */
public class EmployeeView extends javax.swing.JFrame {

    /**
     * Creates new form ThirdFrame
     */
    public EmployeeView() {
        initComponents();
    }
    private RoomController roomController = new RoomController();
    private ServiceController serviceController = new ServiceController();
    private CustomerController customerController = new CustomerController();
    private BookingController bookingController = new BookingController();
    private Booking booking = new Booking();
    public static User userLogin = new User();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        roomPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        findRoomButton = new javax.swing.JButton();
        listRoomButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nameRoomTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomTabel = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        findRoomButton1 = new javax.swing.JButton();
        findRoomButton2 = new javax.swing.JButton();
        findRoomButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        svPanel = new javax.swing.JPanel();
        dxButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        findSvButton = new javax.swing.JButton();
        listSvButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameSvTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        svTabel = new javax.swing.JTable();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dxButton1 = new javax.swing.JButton();
        findCusButton = new javax.swing.JButton();
        listCusButton = new javax.swing.JButton();
        addressCusTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IndentityCusTxt = new javax.swing.JTextField();
        nameCusTxt = new javax.swing.JTextField();
        phoneCusTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        monthCusTxt = new javax.swing.JTextField();
        yearCusTxt = new javax.swing.JTextField();
        dayCusTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkNameLabel = new javax.swing.JLabel();
        checkDateLabel = new javax.swing.JLabel();
        checkPhoneLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELLO EMPLOYEE");
        setPreferredSize(new java.awt.Dimension(907, 551));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(68, 92));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(907, 551));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        roomPanel.setPreferredSize(new java.awt.Dimension(907, 551));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Room Select ");

        findRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findRoomButton.setText("Search");
        findRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomButtonActionPerformed(evt);
            }
        });

        listRoomButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listRoomButton.setText("Choose");
        listRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRoomButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");

        nameRoomTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameRoomTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameRoomTxtMouseClicked(evt);
            }
        });
        nameRoomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRoomTxtActionPerformed(evt);
            }
        });

        roomTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(roomTabel);

        findRoomButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findRoomButton1.setText("Arrange");
        findRoomButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomButton1ActionPerformed(evt);
            }
        });

        findRoomButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findRoomButton2.setText("Min Price");
        findRoomButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomButton2ActionPerformed(evt);
            }
        });

        findRoomButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findRoomButton3.setText("Max Price");
        findRoomButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomPanelLayout = new javax.swing.GroupLayout(roomPanel);
        roomPanel.setLayout(roomPanelLayout);
        roomPanelLayout.setHorizontalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(findRoomButton)
                        .addGap(119, 119, 119)
                        .addComponent(listRoomButton)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2))
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(findRoomButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(findRoomButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(findRoomButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roomPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(nameRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roomPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        roomPanelLayout.setVerticalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(114, 114, 114)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listRoomButton)
                    .addComponent(findRoomButton)
                    .addComponent(jButton2))
                .addGap(34, 34, 34)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                        .addComponent(findRoomButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findRoomButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findRoomButton2)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Room", roomPanel);

        dxButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton3.setText("Logout");
        dxButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Service Select");

        findSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findSvButton.setText("Search");
        findSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findSvButtonActionPerformed(evt);
            }
        });

        listSvButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listSvButton.setText("Choose");
        listSvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSvButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        nameSvTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameSvTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameSvTxtMouseClicked(evt);
            }
        });
        nameSvTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSvTxtActionPerformed(evt);
            }
        });

        svTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(svTabel);

        javax.swing.GroupLayout svPanelLayout = new javax.swing.GroupLayout(svPanel);
        svPanel.setLayout(svPanelLayout);
        svPanelLayout.setHorizontalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(248, 248, 248)
                .addComponent(dxButton3))
            .addGroup(svPanelLayout.createSequentialGroup()
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(svPanelLayout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(svPanelLayout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(jLabel4)
                            .addGap(88, 88, 88)
                            .addComponent(nameSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, svPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(findSvButton)
                        .addGap(160, 160, 160)
                        .addComponent(listSvButton)))
                .addGap(0, 201, Short.MAX_VALUE))
        );
        svPanelLayout.setVerticalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svPanelLayout.createSequentialGroup()
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton3)
                    .addComponent(jLabel3))
                .addGap(127, 127, 127)
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listSvButton)
                    .addComponent(findSvButton))
                .addGap(50, 50, 50)
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameSvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service", svPanel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("CUSTOMER INFORMATION");

        dxButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dxButton1.setText("Logout");
        dxButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxButton1ActionPerformed(evt);
            }
        });

        findCusButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findCusButton.setText("Book");
        findCusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCusButtonActionPerformed(evt);
            }
        });

        listCusButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listCusButton.setText("EXPORT");
        listCusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCusButtonActionPerformed(evt);
            }
        });

        addressCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Phone");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Indentity Num");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Address");

        IndentityCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IndentityCusTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IndentityCusTxtMouseClicked(evt);
            }
        });

        nameCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameCusTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameCusTxtMouseClicked(evt);
            }
        });

        phoneCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneCusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCusTxtActionPerformed(evt);
            }
        });

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookId", "CustomerId", "CustomerName", "RoomId", "ServiceId", "Employee", "TimeCheckIn", "TimeCheckOut"
            }
        ));
        jScrollPane3.setViewportView(bookingTable);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Date Check Out");

        monthCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yearCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dayCusTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("dd");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("yyyy");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("mm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(251, 251, 251)
                .addComponent(yearCusTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(namePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(433, 433, 433))
                                .addGroup(namePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addressCusTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                            .addComponent(phoneCusTxt)
                                            .addComponent(IndentityCusTxt)
                                            .addComponent(nameCusTxt))
                                        .addGroup(namePanelLayout.createSequentialGroup()
                                            .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dayCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(namePanelLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel15)))
                                            .addGap(34, 34, 34)
                                            .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(monthCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(namePanelLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel17)
                                                    .addGap(114, 114, 114)
                                                    .addComponent(jLabel16))))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                        .addComponent(listCusButton)
                        .addGap(34, 34, 34))))
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(findCusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IndentityCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                        .addComponent(listCusButton)
                        .addGap(34, 34, 34)))
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dayCusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findCusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Customer", namePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findCusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCusButtonActionPerformed
        // TODO add your handling code here:
        String name = nameCusTxt.getText();
        if (name.isEmpty()) {
            checkNameLabel.setText("Input name");
            return;
        } else {
            checkNameLabel.setText("");
        }

        String phone = phoneCusTxt.getText();
        if (phone.isEmpty()) {
            checkPhoneLabel.setText("Input Phone");
            return;
        } else {
            checkPhoneLabel.setText("");
        }

        String customerId = IdGenerator.generateEmployeeId(4);
        Customer customer = new Customer(customerId, name, addressCusTxt.getText(), IndentityCusTxt.getText(), phone);

        booking.setBookId(IdGenerator.generateEmployeeId(6));
        booking.setCustomerId(customerId);
        booking.setCustomerName(name);

        String employeeId = userLogin.getEmployeeId();
        Logger.info(employeeId);
        booking.setEmployeeId(employeeId);

        String day = dayCusTxt.getText();
        if (day.isEmpty() || day.length() < 2) {
            checkDateLabel.setText("Day format wrong");
            return;
        }
        String month = monthCusTxt.getText();
        if (month.isEmpty() || month.length() < 2) {
            checkDateLabel.setText("Month format wrong");
            return;
        }
        String date = yearCusTxt.getText() + "-" + month + "-" + day;

        if (!isValid(date)) {
            checkDateLabel.setText("Date wrong");
            return;
        }

        if (java.time.LocalDate.now().toString().compareTo(date) >= 0) {
            checkDateLabel.setText("Date wrong");
            return;
        }
        Date dateCheckOut = Date.valueOf(date);
        booking.setTimeCheckOut(dateCheckOut);

        //Check input
        if (booking.getRoomID() == null) {
            JOptionPane.showMessageDialog(this, "Room not selected");
            return;
        }

        if (booking.getServiceId() == null) {
            JOptionPane.showMessageDialog(this, "Service not selected");
            return;
        }

        boolean check = customerController.insertCustomer(customer);
        if (check) {
            Logger.info("Customer Insert success");
        } else {
            Logger.error("Insert false");
        }

        check = bookingController.insertBooking(booking);
        if (check) {
            Logger.info("Booking Insert success");
        } else {
            Logger.error("Insert false");
        }
        reloadTableBooking();


    }//GEN-LAST:event_findCusButtonActionPerformed

    private void dxButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_dxButton1ActionPerformed

    private void dxButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxButton3ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_dxButton3ActionPerformed

    private void nameSvTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSvTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSvTxtActionPerformed

    private void listCusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCusButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = bookingTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "The book is not selected");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
        String bookingId = (String) model.getValueAt(selectedRow, 0);
        Bill bill = new BillDao().findBillId(bookingId);
        ExportBill.bill(bill);
        JOptionPane.showMessageDialog(this, "Export success");


    }//GEN-LAST:event_listCusButtonActionPerformed

    private void listRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRoomButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = roomTabel.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Room not selected");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) roomTabel.getModel();
        String status = (String) model.getValueAt(selectedRow, 4);
        if (status.equals("F")) {
            JOptionPane.showMessageDialog(this, "Room not empty");
            return;
        }
        String roomId = (String) model.getValueAt(selectedRow, 0);
        booking.setRoomID(roomId);
        JOptionPane.showMessageDialog(this, "Room selected success");

    }//GEN-LAST:event_listRoomButtonActionPerformed

    private void findRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomButtonActionPerformed
        // TODO add your handling code here:
        String name = nameRoomTxt.getText();
        List<Room> listRoom = roomController.findRoom(name);
        showDataRoom(listRoom);


    }//GEN-LAST:event_findRoomButtonActionPerformed

    private void nameRoomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRoomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRoomTxtActionPerformed

    private void findSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findSvButtonActionPerformed
        // TODO add your handling code here:
        String name = nameSvTxt.getText();
        List<Service> listService = serviceController.findService(name);
        showDataService(listService);
    }//GEN-LAST:event_findSvButtonActionPerformed

    private void listSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSvButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = svTabel.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "The service is not selected");
            return;

        }
        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();
        String serviceId = (String) model.getValueAt(selectedRow, 0);
        booking.setServiceId(serviceId);
        JOptionPane.showMessageDialog(this, "Service Selected success");
    }//GEN-LAST:event_listSvButtonActionPerformed

    private void phoneCusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneCusTxtActionPerformed

    private void findRoomButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomButton1ActionPerformed
        // TODO add your handling code here:
        List<Room> listRoom = roomController.arrangeRoom();
        showDataRoom(listRoom);
    }//GEN-LAST:event_findRoomButton1ActionPerformed

    private void findRoomButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomButton2ActionPerformed
        // TODO add your handling code here:
        List<Room> listRoom = roomController.minRoom();
        showDataRoom(listRoom);
    }//GEN-LAST:event_findRoomButton2ActionPerformed

    private void findRoomButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomButton3ActionPerformed
        // TODO add your handling code here:
        List<Room> listRoom = roomController.maxRoom();
        showDataRoom(listRoom);
    }//GEN-LAST:event_findRoomButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RoomDao roomDao = new RoomDao();
        int countUpdate = roomDao.refreshRoom();
        if (countUpdate > 0) {
            JOptionPane.showMessageDialog(this, "Refresh success full");

        } else {
            JOptionPane.showMessageDialog(this, "All Room Empty");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Logout Success");

        LoginView firstFrame = new LoginView();
        firstFrame.setVisible(true);
        firstFrame.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        resetText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void nameRoomTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameRoomTxtMouseClicked
        nameRoomTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRoomTxtMouseClicked

    private void nameSvTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSvTxtMouseClicked
        nameSvTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSvTxtMouseClicked

    private void nameCusTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameCusTxtMouseClicked
        nameCusTxt.setText("");
        IndentityCusTxt.setText("");
        phoneCusTxt.setText("");
        addressCusTxt.setText("");
        dayCusTxt.setText("");
        monthCusTxt.setText("");
        yearCusTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCusTxtMouseClicked

    private void IndentityCusTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IndentityCusTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IndentityCusTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public void runFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeView thirdFrame = new EmployeeView();
                thirdFrame.setVisible(true);
                thirdFrame.reloadTableBooking();
                thirdFrame.reloadTableRoom();
                thirdFrame.reloadTableService();
                thirdFrame.setLocationRelativeTo(null);;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IndentityCusTxt;
    private javax.swing.JTextField addressCusTxt;
    private javax.swing.JTable bookingTable;
    private javax.swing.JLabel checkDateLabel;
    private javax.swing.JLabel checkNameLabel;
    private javax.swing.JLabel checkPhoneLabel;
    private javax.swing.JTextField dayCusTxt;
    private javax.swing.JButton dxButton1;
    private javax.swing.JButton dxButton3;
    private javax.swing.JButton findCusButton;
    private javax.swing.JButton findRoomButton;
    private javax.swing.JButton findRoomButton1;
    private javax.swing.JButton findRoomButton2;
    private javax.swing.JButton findRoomButton3;
    private javax.swing.JButton findSvButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listCusButton;
    private javax.swing.JButton listRoomButton;
    private javax.swing.JButton listSvButton;
    private javax.swing.JTextField monthCusTxt;
    private javax.swing.JTextField nameCusTxt;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameRoomTxt;
    private javax.swing.JTextField nameSvTxt;
    private javax.swing.JTextField phoneCusTxt;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JTable roomTabel;
    private javax.swing.JPanel svPanel;
    private javax.swing.JTable svTabel;
    private javax.swing.JTextField yearCusTxt;
    // End of variables declaration//GEN-END:variables
    public void reloadTableRoom() {
        List<Room> listRoom = roomController.returnAllRoom();
        DefaultTableModel model = (DefaultTableModel) roomTabel.getModel();

        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        // Add new data
        for (Room room : listRoom) {
            model.addRow(new Object[]{room.getRoomId(), room.getName(), room.getType(), room.getPrice(), room.getStatus()});
        }

    }

    private void showDataRoom(List<Room> listRoom) {
        DefaultTableModel model = (DefaultTableModel) roomTabel.getModel();

        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        // Add new data
        for (Room room : listRoom) {
            model.addRow(new Object[]{room.getRoomId(), room.getName(), room.getType(), room.getPrice(), room.getStatus()});
        }
    }

    private void showDataService(List<Service> listService) {
        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();

        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        // Add new data
        for (Service service : listService) {
            model.addRow(new Object[]{service.getServiceId(), service.getName(), service.getPrice()});
        }
    }

    public void reloadTableService() {
        List<Service> listService = serviceController.returnAllService();
        DefaultTableModel model = (DefaultTableModel) svTabel.getModel();

        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        // Add new data
        for (Service service : listService) {
            model.addRow(new Object[]{service.getServiceId(), service.getName(), service.getPrice()});
        }

    }

    public void reloadTableBooking() {
        List<Booking> listBooking = bookingController.returnAllBooking();
        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();

        // Delete old data
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        // Add new data
        for (Booking booking : listBooking) {
            model.addRow(new Object[]{booking.getBookId(), booking.getCustomerId(), booking.getCustomerName(), booking.getRoomID(), booking.getServiceId(), booking.getEmployeeId(), booking.getTimeCheckIn(), booking.getTimeCheckOut()});
        }
    }

    public static boolean isValid(final String date) {

        boolean valid = false;

        try {

            // ResolverStyle.STRICT for 30, 31 days checking, and also leap year.
            LocalDate.parse(date,
                    DateTimeFormatter.ofPattern("uuuu-M-d")
                            .withResolverStyle(ResolverStyle.STRICT)
            );

            valid = true;

        } catch (DateTimeParseException e) {
            e.printStackTrace();
            valid = false;
        }

        return valid;
    }
    
    public void resetText(){
        nameRoomTxt.setText("");
        nameSvTxt.setText("");
        nameCusTxt.setText("");
        IndentityCusTxt.setText("");
        phoneCusTxt.setText("");
        addressCusTxt.setText("");
        dayCusTxt.setText("");
        monthCusTxt.setText("");
        yearCusTxt.setText("");
    }

}
